---
title: HMetadataType
---

A metadata type representation. \
Supports `All`, `Text` and `Visual` types. \

# Methods

## all

`all -> HMetadataType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hmetadatatype.rs#L39) </span> \

Creates an All `HMetadataType`. \

#### Returns

An `HMetadataType`.

#### Examples

```r
HMetadataType$all
```

_________

## text

`text -> HMetadataType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hmetadatatype.rs#L62) </span> \

Creates a Text `HMetadataType`. \

#### Returns

An `HMetadataType`.

#### Examples

```r
HMetadataType$text
```

_________

## visual

`visual -> HMetadataType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hmetadatatype.rs#L85) </span> \

Creates a Visual `HMetadataType`. \

#### Returns

An `HMetadataType`.

#### Examples

```r
HMetadataType$visual
```

_________

## print

`print()` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hmetadatatype.rs#L109) </span> \

Prints the `HMetadataType`. \
Differently from R's behaviour, `print` doesn't return the value invisibly. \

#### Examples

```r
metadatatype = HMetadataType$complex64
metadatatype$print()

# or similarly:
print(metadatatype)
```

_________

## eq

`eq(other: HMetadataType) -> bool` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hmetadatatype.rs#L142) </span> \

Equality with another `HMetadataType`.

#### Arguments

* `other` \
An `HMetadataType`. \

#### Returns

A `bool`.

#### Examples

```r
metadatatype1 = HMetadataType$all
metadatatype2 = HMetadataType$all
metadatatype1$eq(metadatatype2) # TRUE

# or similarly:
metadatatype1 == metadatatype2
```

_________

## ne

`ne(other: HMetadataType) -> bool` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hmetadatatype.rs#L175) </span> \

Difference with another `HMetadataType`.

#### Arguments

* `other` \
An `HMetadataType`. \

#### Returns

A `bool`.

#### Examples

```r
metadatatype1 = HMetadataType$all
metadatatype2 = HMetadataType$all
metadatatype1$ne(metadatatype2) # FALSE

# or similarly:
metadatatype1 != metadatatype2
```

_________
