---
title: HResamplerType
---

A resampler type representation. \
Supports `FftFixedIn`, `FftFixedInOut`, `FftFixedOut`, `SincFixedIn` and `SincFixedOut` types. \

# Methods

## fft_fixed_in

`fft_fixed_in -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L42) </span> \

Creates a `FftFixedIn` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$fft_fixed_in
```

_________

## fft_fixed_in_out

`fft_fixed_in_out -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L65) </span> \

Creates a `FftFixedInOut` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$fft_fixed_in_out
```

_________

## fft_fixed_out

`fft_fixed_out -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L88) </span> \

Creates a `FftFixedOut` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$fft_fixed_out
```

_________

## sinc_fixed_in

`sinc_fixed_in -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L111) </span> \

Creates a `SincFixedIn` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$sinc_fixed_in
```

_________

## sinc_fixed_out

`sinc_fixed_out -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L134) </span> \

Creates a `SincFixedOut` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$sinc_fixed_out
```

_________

## fast_fixed_in

`fast_fixed_in -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L157) </span> \

Creates a `FastFixedIn` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$fast_fixed_in
```

_________

## fast_fixed_out

`fast_fixed_out -> HResamplerType` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L180) </span> \

Creates a `FastFixedOut` `HResamplerType`. \

#### Returns

An `HResamplerType`. \

#### Examples

```r
hresamplertype = HResamplerType$fast_fixed_out
```

_________

## print

`print()` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L204) </span> \

Prints the `HResamplerType`. \
Differently from R's behaviour, `print` doesn't return the value invisibly. \

#### Examples

```r
hresamplertype = HResamplerType$sinc_fixed_in
hresamplertype$print()

# or similarly:
print(hresamplertype)
```

_________

## eq

`eq(other: HResamplerType) -> bool` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L237) </span> \

Equality with another `HResamplerType`.

#### Arguments

* `other` \
An `HResamplerType`. \

#### Returns

A `bool`.

#### Examples

```r
hresamplertype1 = HResamplerType$sinc_fixed_in
hresamplertype2 = HResamplerType$sinc_fixed_in
hresamplertype1$eq(hresamplertype2) # TRUE

# or similarly:
hresamplertype1 == hresamplertype2
```

_________

## ne

`ne(other: HResamplerType) -> bool` <span style="float: right;"> [source](https://www.github.com/daniellga/harmonium/blob/master/r-harmonium/src/rust/src/./hresamplertype.rs#L270) </span> \

Difference with another `HResamplerType`.

#### Arguments

* `other` \
An `HResamplerType`. \

#### Returns

A `bool`.

#### Examples

```r
hresamplertype1 = HResamplerType$sinc_fixed_in
hresamplertype2 = HResamplerType$sinc_fixed_in
hresamplertype1$ne(hresamplertype2) # FALSE

# or similarly:
hresamplertype1 != hresamplertype2
```

_________
