[package]
name = "harmonium-resample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harmonium-core = { path = "../harmonium-core" }
rubato = "*"
arrow2 = "0.17"
num-traits = "*"
