project:
  type: website

website:
  title: "Harmonium"
  navbar:
    tools:
      - icon: github
        href: https://github.com/daniellga/harmonium
        text: GitHub
  sidebar:
    style: "docked"
    contents:
      - section: "Classes"
        contents: docs/* 

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1000px



