project:
  type: website
  output-dir: ../../docs

website:
  title: "Harmonium"
  navbar:
    tools:
      - icon: github
        href: https://github.com/daniellga/harmonium
        text: GitHub
  sidebar:
    style: "docked"
    contents:
      - section: "Classes"
        contents: contents/* 

format:
  html:
    theme:
      dark: flatly
      light: darkly
    highlight-style: github
    css: styles.css
    toc: true
    grid:
      body-width: 1000px
