[package]
name = "harmonium-stft"
version = "0.1.0"
edition = "2021"

[dependencies]
harmonium-core = { workspace = true }
harmonium-fft = { workspace = true }
rustfft = { workspace = true }
realfft = { workspace = true }
ndarray = { workspace = true }

