test_that(
  "all elements that should be exported are exported",
  {
    expect_no_error(harmonium::HArray)
    expect_no_error(harmonium::HMatrix)
    expect_no_error(harmonium::HAudio)
    expect_no_error(harmonium::HDataType)
    expect_no_error(harmonium::HAudioSink)
    expect_no_error(harmonium::HResampler)
    expect_no_error(harmonium::HResamplerType)
    expect_no_error(harmonium::HWindow)
    expect_no_error(harmonium::HFile)
    expect_no_error(harmonium::HConfig)
  }


)


# S3method("!=",HArray)
# S3method("!=",HAudio)
# S3method("!=",HDataType)
# S3method("!=",HMatrix)
# S3method("!=",HMetadataType)
# S3method("!=",HResamplerType)
# S3method("$",HArray)
# S3method("$",HAudio)
# S3method("$",HAudioSink)
# S3method("$",HDataType)
# S3method("$",HError)
# S3method("$",HFile)
# S3method("$",HInterpolationParams)
# S3method("$",HMatrix)
# S3method("$",HMetadataType)
# S3method("$",HResampler)
# S3method("$",HResamplerType)
# S3method("$",HWindow)
# S3method("==",HArray)
# S3method("==",HAudio)
# S3method("==",HDataType)
# S3method("==",HMatrix)
# S3method("==",HMetadataType)
# S3method("==",HResamplerType)
# S3method("[[",HArray)
# S3method("[[",HAudio)
# S3method("[[",HAudioSink)
# S3method("[[",HDataType)
# S3method("[[",HError)
# S3method("[[",HFile)
# S3method("[[",HInterpolationParams)
# S3method("[[",HMatrix)
# S3method("[[",HMetadataType)
# S3method("[[",HResampler)
# S3method("[[",HResamplerType)
# S3method("[[",HWindow)
# S3method(arrow::as_arrow_array,HArray)
# S3method(arrow::as_arrow_array,HMatrix)
# S3method(print,HArray)
# S3method(print,HAudio)
# S3method(print,HDataType)
# S3method(print,HMatrix)
# S3method(print,HMetadataType)
# S3method(print,HResampler)
# S3method(print,HResamplerType)
