name: Create docs for github pages

on:
  push:
    branches:
      - master

jobs:
  run_commands:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Run commands
        run: |
          rm -rf docs
          cd r-harmonium/docs
          quarto render

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Git has changes."
          if [ $? -eq 0 ]; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs['exit-code'] != '0'
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

          git add .
          git status
          git commit -m "Created github pages docs"
          git push origin master

